name: build and publish docker image
on:
  schedule:
    - cron: '0 0 1 * *'
  push:
    paths:
    - 'Dockerfile'
    - '.github/workflows/build-and-publish-docker-image.yml'
jobs:
  build:
    name: Build texlive-full
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Build
        run: docker build -t texlive-full .
      - name: Test
        run: docker run --rm texlive-full latexmk --version
      - name: Deploy
        run: |
          TAG="ghcr.io/pbizopoulos/texlive-full"
          docker tag texlive-full ${TAG}:latest
          echo ${{ secrets.GCR_PAT }} | docker login ghcr.io --username pbizopoulos --password-stdin
          docker push $TAG
